# Generated by Django 4.0.6 on 2023-10-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.TextField()),
                ('description', models.TextField()),
                ('age_restrictions', models.TextField()),
                ('company', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('address', models.TextField()),
                ('img_link', models.TextField()),
                ('is_registered', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Мероприятия',
                'verbose_name_plural': 'Мероприятия',
                'db_table': 'events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reminders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('reminder_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Напоминания',
                'verbose_name_plural': 'Напоминания',
                'db_table': 'reminders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(blank=True, null=True)),
                ('is_registered', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Посетители',
                'verbose_name_plural': 'Посетители',
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
