# Generated by Django 4.0.6 on 2023-09-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YMaps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.TextField()),
                ('description', models.TextField()),
                ('age_restrictions', models.TextField()),
                ('company', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('address', models.TextField()),
                ('img', models.TextField()),
                ('is_registered', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Мероприятия',
                'verbose_name_plural': 'Мероприятия',
                'db_table': 'event',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
